/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthModulesIndexRouteImport } from './routes/_auth/modules/index'
import { Route as AuthClassroomsIndexRouteImport } from './routes/_auth/classrooms/index'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'
import { Route as AuthAdminDomainRequestsRouteImport } from './routes/_auth/admin/domain-requests'
import { Route as AuthClassroomsClassroomIdIndexRouteImport } from './routes/_auth/classrooms/$classroomId/index'
import { Route as AuthClassroomsClassroomIdSlideshowRouteImport } from './routes/_auth/classrooms/$classroomId/slideshow'
import { Route as AuthClassroomsClassroomIdGradesRouteImport } from './routes/_auth/classrooms/$classroomId/grades'
import { Route as AuthClassroomsClassroomIdAttendanceIndexRouteImport } from './routes/_auth/classrooms/$classroomId/attendance/index'
import { Route as AuthClassroomsClassroomIdAttendanceSessionIdRouteImport } from './routes/_auth/classrooms/$classroomId/attendance/$sessionId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModulesIndexRoute = AuthModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClassroomsIndexRoute = AuthClassroomsIndexRouteImport.update({
  id: '/classrooms/',
  path: '/classrooms/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminDomainRequestsRoute = AuthAdminDomainRequestsRouteImport.update({
  id: '/admin/domain-requests',
  path: '/admin/domain-requests',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClassroomsClassroomIdIndexRoute =
  AuthClassroomsClassroomIdIndexRouteImport.update({
    id: '/classrooms/$classroomId/',
    path: '/classrooms/$classroomId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthClassroomsClassroomIdSlideshowRoute =
  AuthClassroomsClassroomIdSlideshowRouteImport.update({
    id: '/classrooms/$classroomId/slideshow',
    path: '/classrooms/$classroomId/slideshow',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthClassroomsClassroomIdGradesRoute =
  AuthClassroomsClassroomIdGradesRouteImport.update({
    id: '/classrooms/$classroomId/grades',
    path: '/classrooms/$classroomId/grades',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthClassroomsClassroomIdAttendanceIndexRoute =
  AuthClassroomsClassroomIdAttendanceIndexRouteImport.update({
    id: '/classrooms/$classroomId/attendance/',
    path: '/classrooms/$classroomId/attendance/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthClassroomsClassroomIdAttendanceSessionIdRoute =
  AuthClassroomsClassroomIdAttendanceSessionIdRouteImport.update({
    id: '/classrooms/$classroomId/attendance/$sessionId',
    path: '/classrooms/$classroomId/attendance/$sessionId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthDashboardRoute
  '/admin/domain-requests': typeof AuthAdminDomainRequestsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/classrooms/': typeof AuthClassroomsIndexRoute
  '/modules/': typeof AuthModulesIndexRoute
  '/classrooms/$classroomId/grades': typeof AuthClassroomsClassroomIdGradesRoute
  '/classrooms/$classroomId/slideshow': typeof AuthClassroomsClassroomIdSlideshowRoute
  '/classrooms/$classroomId/': typeof AuthClassroomsClassroomIdIndexRoute
  '/classrooms/$classroomId/attendance/$sessionId': typeof AuthClassroomsClassroomIdAttendanceSessionIdRoute
  '/classrooms/$classroomId/attendance/': typeof AuthClassroomsClassroomIdAttendanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthDashboardRoute
  '/admin/domain-requests': typeof AuthAdminDomainRequestsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/classrooms': typeof AuthClassroomsIndexRoute
  '/modules': typeof AuthModulesIndexRoute
  '/classrooms/$classroomId/grades': typeof AuthClassroomsClassroomIdGradesRoute
  '/classrooms/$classroomId/slideshow': typeof AuthClassroomsClassroomIdSlideshowRoute
  '/classrooms/$classroomId': typeof AuthClassroomsClassroomIdIndexRoute
  '/classrooms/$classroomId/attendance/$sessionId': typeof AuthClassroomsClassroomIdAttendanceSessionIdRoute
  '/classrooms/$classroomId/attendance': typeof AuthClassroomsClassroomIdAttendanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/admin/domain-requests': typeof AuthAdminDomainRequestsRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/classrooms/': typeof AuthClassroomsIndexRoute
  '/_auth/modules/': typeof AuthModulesIndexRoute
  '/_auth/classrooms/$classroomId/grades': typeof AuthClassroomsClassroomIdGradesRoute
  '/_auth/classrooms/$classroomId/slideshow': typeof AuthClassroomsClassroomIdSlideshowRoute
  '/_auth/classrooms/$classroomId/': typeof AuthClassroomsClassroomIdIndexRoute
  '/_auth/classrooms/$classroomId/attendance/$sessionId': typeof AuthClassroomsClassroomIdAttendanceSessionIdRoute
  '/_auth/classrooms/$classroomId/attendance/': typeof AuthClassroomsClassroomIdAttendanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/admin/domain-requests'
    | '/admin/users'
    | '/classrooms/'
    | '/modules/'
    | '/classrooms/$classroomId/grades'
    | '/classrooms/$classroomId/slideshow'
    | '/classrooms/$classroomId/'
    | '/classrooms/$classroomId/attendance/$sessionId'
    | '/classrooms/$classroomId/attendance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/admin/domain-requests'
    | '/admin/users'
    | '/classrooms'
    | '/modules'
    | '/classrooms/$classroomId/grades'
    | '/classrooms/$classroomId/slideshow'
    | '/classrooms/$classroomId'
    | '/classrooms/$classroomId/attendance/$sessionId'
    | '/classrooms/$classroomId/attendance'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_auth/dashboard'
    | '/_auth/admin/domain-requests'
    | '/_auth/admin/users'
    | '/_auth/classrooms/'
    | '/_auth/modules/'
    | '/_auth/classrooms/$classroomId/grades'
    | '/_auth/classrooms/$classroomId/slideshow'
    | '/_auth/classrooms/$classroomId/'
    | '/_auth/classrooms/$classroomId/attendance/$sessionId'
    | '/_auth/classrooms/$classroomId/attendance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/modules/': {
      id: '/_auth/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof AuthModulesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/classrooms/': {
      id: '/_auth/classrooms/'
      path: '/classrooms'
      fullPath: '/classrooms/'
      preLoaderRoute: typeof AuthClassroomsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/domain-requests': {
      id: '/_auth/admin/domain-requests'
      path: '/admin/domain-requests'
      fullPath: '/admin/domain-requests'
      preLoaderRoute: typeof AuthAdminDomainRequestsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/classrooms/$classroomId/': {
      id: '/_auth/classrooms/$classroomId/'
      path: '/classrooms/$classroomId'
      fullPath: '/classrooms/$classroomId/'
      preLoaderRoute: typeof AuthClassroomsClassroomIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/classrooms/$classroomId/slideshow': {
      id: '/_auth/classrooms/$classroomId/slideshow'
      path: '/classrooms/$classroomId/slideshow'
      fullPath: '/classrooms/$classroomId/slideshow'
      preLoaderRoute: typeof AuthClassroomsClassroomIdSlideshowRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/classrooms/$classroomId/grades': {
      id: '/_auth/classrooms/$classroomId/grades'
      path: '/classrooms/$classroomId/grades'
      fullPath: '/classrooms/$classroomId/grades'
      preLoaderRoute: typeof AuthClassroomsClassroomIdGradesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/classrooms/$classroomId/attendance/': {
      id: '/_auth/classrooms/$classroomId/attendance/'
      path: '/classrooms/$classroomId/attendance'
      fullPath: '/classrooms/$classroomId/attendance/'
      preLoaderRoute: typeof AuthClassroomsClassroomIdAttendanceIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/classrooms/$classroomId/attendance/$sessionId': {
      id: '/_auth/classrooms/$classroomId/attendance/$sessionId'
      path: '/classrooms/$classroomId/attendance/$sessionId'
      fullPath: '/classrooms/$classroomId/attendance/$sessionId'
      preLoaderRoute: typeof AuthClassroomsClassroomIdAttendanceSessionIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthAdminDomainRequestsRoute: typeof AuthAdminDomainRequestsRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthClassroomsIndexRoute: typeof AuthClassroomsIndexRoute
  AuthModulesIndexRoute: typeof AuthModulesIndexRoute
  AuthClassroomsClassroomIdGradesRoute: typeof AuthClassroomsClassroomIdGradesRoute
  AuthClassroomsClassroomIdSlideshowRoute: typeof AuthClassroomsClassroomIdSlideshowRoute
  AuthClassroomsClassroomIdIndexRoute: typeof AuthClassroomsClassroomIdIndexRoute
  AuthClassroomsClassroomIdAttendanceSessionIdRoute: typeof AuthClassroomsClassroomIdAttendanceSessionIdRoute
  AuthClassroomsClassroomIdAttendanceIndexRoute: typeof AuthClassroomsClassroomIdAttendanceIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthAdminDomainRequestsRoute: AuthAdminDomainRequestsRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthClassroomsIndexRoute: AuthClassroomsIndexRoute,
  AuthModulesIndexRoute: AuthModulesIndexRoute,
  AuthClassroomsClassroomIdGradesRoute: AuthClassroomsClassroomIdGradesRoute,
  AuthClassroomsClassroomIdSlideshowRoute:
    AuthClassroomsClassroomIdSlideshowRoute,
  AuthClassroomsClassroomIdIndexRoute: AuthClassroomsClassroomIdIndexRoute,
  AuthClassroomsClassroomIdAttendanceSessionIdRoute:
    AuthClassroomsClassroomIdAttendanceSessionIdRoute,
  AuthClassroomsClassroomIdAttendanceIndexRoute:
    AuthClassroomsClassroomIdAttendanceIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
