/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherSignupRouteImport } from './routes/teacher.signup'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as TeacherSignupIndexRouteImport } from './routes/teacher.signup.index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings.index'
import { Route as AuthTeacherUsageRouteImport } from './routes/_auth/teacher/usage'
import { Route as AuthTeacherProfileRouteImport } from './routes/_auth/teacher/profile'
import { Route as AuthTeacherDashboardRouteImport } from './routes/_auth/teacher/dashboard'
import { Route as AuthTeacherCalendarRouteImport } from './routes/_auth/teacher/calendar'
import { Route as AuthTeacherAnalyticsRouteImport } from './routes/_auth/teacher/analytics'
import { Route as AuthSettingsWorkspaceRouteImport } from './routes/_auth/settings.workspace'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings.profile'
import { Route as AuthSettingsPrivacyRouteImport } from './routes/_auth/settings.privacy'
import { Route as AuthSettingsAboutRouteImport } from './routes/_auth/settings.about'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'
import { Route as AuthAdminOverviewRouteImport } from './routes/_auth/admin/overview'
import { Route as AuthAdminDomainRequestsRouteImport } from './routes/_auth/admin/domain-requests'
import { Route as AuthAdminAuditLogRouteImport } from './routes/_auth/admin/audit-log'
import { Route as AuthTeacherModulesIndexRouteImport } from './routes/_auth/teacher/modules/index'
import { Route as AuthTeacherClassroomsIndexRouteImport } from './routes/_auth/teacher/classrooms/index'
import { Route as TeacherSignupStep6WelcomeToAgilearnRouteImport } from './routes/teacher.signup.step-6.welcome-to-agilearn'
import { Route as TeacherSignupStep5TeachingLevelsRouteImport } from './routes/teacher.signup.step-5.teaching-levels'
import { Route as TeacherSignupStep4YourSchoolRouteImport } from './routes/teacher.signup.step-4.your-school'
import { Route as TeacherSignupStep3TellUsAboutYouRouteImport } from './routes/teacher.signup.step-3.tell-us-about-you'
import { Route as TeacherSignupStep2VerifyYourEmailRouteImport } from './routes/teacher.signup.step-2.verify-your-email'
import { Route as TeacherSignupStep1CreateYourAccountRouteImport } from './routes/teacher.signup.step-1.create-your-account'
import { Route as AuthTeacherClassroomsClassroomIdIndexRouteImport } from './routes/_auth/teacher/classrooms/$classroomId/index'
import { Route as AuthTeacherClassroomsClassroomIdSlideshowRouteImport } from './routes/_auth/teacher/classrooms/$classroomId/slideshow'
import { Route as AuthTeacherClassroomsClassroomIdGradesRouteImport } from './routes/_auth/teacher/classrooms/$classroomId/grades'
import { Route as AuthTeacherClassroomsClassroomIdAttendanceIndexRouteImport } from './routes/_auth/teacher/classrooms/$classroomId/attendance/index'
import { Route as AuthTeacherClassroomsClassroomIdAttendanceSessionIdRouteImport } from './routes/_auth/teacher/classrooms/$classroomId/attendance/$sessionId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSignupRoute = TeacherSignupRouteImport.update({
  id: '/teacher/signup',
  path: '/teacher/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const TeacherSignupIndexRoute = TeacherSignupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherSignupRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthTeacherUsageRoute = AuthTeacherUsageRouteImport.update({
  id: '/teacher/usage',
  path: '/teacher/usage',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeacherProfileRoute = AuthTeacherProfileRouteImport.update({
  id: '/teacher/profile',
  path: '/teacher/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeacherDashboardRoute = AuthTeacherDashboardRouteImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeacherCalendarRoute = AuthTeacherCalendarRouteImport.update({
  id: '/teacher/calendar',
  path: '/teacher/calendar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeacherAnalyticsRoute = AuthTeacherAnalyticsRouteImport.update({
  id: '/teacher/analytics',
  path: '/teacher/analytics',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsWorkspaceRoute = AuthSettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsPrivacyRoute = AuthSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsAboutRoute = AuthSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminOverviewRoute = AuthAdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminDomainRequestsRoute = AuthAdminDomainRequestsRouteImport.update({
  id: '/admin/domain-requests',
  path: '/admin/domain-requests',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminAuditLogRoute = AuthAdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeacherModulesIndexRoute = AuthTeacherModulesIndexRouteImport.update({
  id: '/teacher/modules/',
  path: '/teacher/modules/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeacherClassroomsIndexRoute =
  AuthTeacherClassroomsIndexRouteImport.update({
    id: '/teacher/classrooms/',
    path: '/teacher/classrooms/',
    getParentRoute: () => AuthRoute,
  } as any)
const TeacherSignupStep6WelcomeToAgilearnRoute =
  TeacherSignupStep6WelcomeToAgilearnRouteImport.update({
    id: '/step-6/welcome-to-agilearn',
    path: '/step-6/welcome-to-agilearn',
    getParentRoute: () => TeacherSignupRoute,
  } as any)
const TeacherSignupStep5TeachingLevelsRoute =
  TeacherSignupStep5TeachingLevelsRouteImport.update({
    id: '/step-5/teaching-levels',
    path: '/step-5/teaching-levels',
    getParentRoute: () => TeacherSignupRoute,
  } as any)
const TeacherSignupStep4YourSchoolRoute =
  TeacherSignupStep4YourSchoolRouteImport.update({
    id: '/step-4/your-school',
    path: '/step-4/your-school',
    getParentRoute: () => TeacherSignupRoute,
  } as any)
const TeacherSignupStep3TellUsAboutYouRoute =
  TeacherSignupStep3TellUsAboutYouRouteImport.update({
    id: '/step-3/tell-us-about-you',
    path: '/step-3/tell-us-about-you',
    getParentRoute: () => TeacherSignupRoute,
  } as any)
const TeacherSignupStep2VerifyYourEmailRoute =
  TeacherSignupStep2VerifyYourEmailRouteImport.update({
    id: '/step-2/verify-your-email',
    path: '/step-2/verify-your-email',
    getParentRoute: () => TeacherSignupRoute,
  } as any)
const TeacherSignupStep1CreateYourAccountRoute =
  TeacherSignupStep1CreateYourAccountRouteImport.update({
    id: '/step-1/create-your-account',
    path: '/step-1/create-your-account',
    getParentRoute: () => TeacherSignupRoute,
  } as any)
const AuthTeacherClassroomsClassroomIdIndexRoute =
  AuthTeacherClassroomsClassroomIdIndexRouteImport.update({
    id: '/teacher/classrooms/$classroomId/',
    path: '/teacher/classrooms/$classroomId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTeacherClassroomsClassroomIdSlideshowRoute =
  AuthTeacherClassroomsClassroomIdSlideshowRouteImport.update({
    id: '/teacher/classrooms/$classroomId/slideshow',
    path: '/teacher/classrooms/$classroomId/slideshow',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTeacherClassroomsClassroomIdGradesRoute =
  AuthTeacherClassroomsClassroomIdGradesRouteImport.update({
    id: '/teacher/classrooms/$classroomId/grades',
    path: '/teacher/classrooms/$classroomId/grades',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTeacherClassroomsClassroomIdAttendanceIndexRoute =
  AuthTeacherClassroomsClassroomIdAttendanceIndexRouteImport.update({
    id: '/teacher/classrooms/$classroomId/attendance/',
    path: '/teacher/classrooms/$classroomId/attendance/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTeacherClassroomsClassroomIdAttendanceSessionIdRoute =
  AuthTeacherClassroomsClassroomIdAttendanceSessionIdRouteImport.update({
    id: '/teacher/classrooms/$classroomId/attendance/$sessionId',
    path: '/teacher/classrooms/$classroomId/attendance/$sessionId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/teacher/signup': typeof TeacherSignupRouteWithChildren
  '/admin/audit-log': typeof AuthAdminAuditLogRoute
  '/admin/domain-requests': typeof AuthAdminDomainRequestsRoute
  '/admin/overview': typeof AuthAdminOverviewRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/settings/about': typeof AuthSettingsAboutRoute
  '/settings/privacy': typeof AuthSettingsPrivacyRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/workspace': typeof AuthSettingsWorkspaceRoute
  '/teacher/analytics': typeof AuthTeacherAnalyticsRoute
  '/teacher/calendar': typeof AuthTeacherCalendarRoute
  '/teacher/dashboard': typeof AuthTeacherDashboardRoute
  '/teacher/profile': typeof AuthTeacherProfileRoute
  '/teacher/usage': typeof AuthTeacherUsageRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/teacher/signup/': typeof TeacherSignupIndexRoute
  '/teacher/signup/step-1/create-your-account': typeof TeacherSignupStep1CreateYourAccountRoute
  '/teacher/signup/step-2/verify-your-email': typeof TeacherSignupStep2VerifyYourEmailRoute
  '/teacher/signup/step-3/tell-us-about-you': typeof TeacherSignupStep3TellUsAboutYouRoute
  '/teacher/signup/step-4/your-school': typeof TeacherSignupStep4YourSchoolRoute
  '/teacher/signup/step-5/teaching-levels': typeof TeacherSignupStep5TeachingLevelsRoute
  '/teacher/signup/step-6/welcome-to-agilearn': typeof TeacherSignupStep6WelcomeToAgilearnRoute
  '/teacher/classrooms/': typeof AuthTeacherClassroomsIndexRoute
  '/teacher/modules/': typeof AuthTeacherModulesIndexRoute
  '/teacher/classrooms/$classroomId/grades': typeof AuthTeacherClassroomsClassroomIdGradesRoute
  '/teacher/classrooms/$classroomId/slideshow': typeof AuthTeacherClassroomsClassroomIdSlideshowRoute
  '/teacher/classrooms/$classroomId/': typeof AuthTeacherClassroomsClassroomIdIndexRoute
  '/teacher/classrooms/$classroomId/attendance/$sessionId': typeof AuthTeacherClassroomsClassroomIdAttendanceSessionIdRoute
  '/teacher/classrooms/$classroomId/attendance/': typeof AuthTeacherClassroomsClassroomIdAttendanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/audit-log': typeof AuthAdminAuditLogRoute
  '/admin/domain-requests': typeof AuthAdminDomainRequestsRoute
  '/admin/overview': typeof AuthAdminOverviewRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/settings/about': typeof AuthSettingsAboutRoute
  '/settings/privacy': typeof AuthSettingsPrivacyRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/workspace': typeof AuthSettingsWorkspaceRoute
  '/teacher/analytics': typeof AuthTeacherAnalyticsRoute
  '/teacher/calendar': typeof AuthTeacherCalendarRoute
  '/teacher/dashboard': typeof AuthTeacherDashboardRoute
  '/teacher/profile': typeof AuthTeacherProfileRoute
  '/teacher/usage': typeof AuthTeacherUsageRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/teacher/signup': typeof TeacherSignupIndexRoute
  '/teacher/signup/step-1/create-your-account': typeof TeacherSignupStep1CreateYourAccountRoute
  '/teacher/signup/step-2/verify-your-email': typeof TeacherSignupStep2VerifyYourEmailRoute
  '/teacher/signup/step-3/tell-us-about-you': typeof TeacherSignupStep3TellUsAboutYouRoute
  '/teacher/signup/step-4/your-school': typeof TeacherSignupStep4YourSchoolRoute
  '/teacher/signup/step-5/teaching-levels': typeof TeacherSignupStep5TeachingLevelsRoute
  '/teacher/signup/step-6/welcome-to-agilearn': typeof TeacherSignupStep6WelcomeToAgilearnRoute
  '/teacher/classrooms': typeof AuthTeacherClassroomsIndexRoute
  '/teacher/modules': typeof AuthTeacherModulesIndexRoute
  '/teacher/classrooms/$classroomId/grades': typeof AuthTeacherClassroomsClassroomIdGradesRoute
  '/teacher/classrooms/$classroomId/slideshow': typeof AuthTeacherClassroomsClassroomIdSlideshowRoute
  '/teacher/classrooms/$classroomId': typeof AuthTeacherClassroomsClassroomIdIndexRoute
  '/teacher/classrooms/$classroomId/attendance/$sessionId': typeof AuthTeacherClassroomsClassroomIdAttendanceSessionIdRoute
  '/teacher/classrooms/$classroomId/attendance': typeof AuthTeacherClassroomsClassroomIdAttendanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/teacher/signup': typeof TeacherSignupRouteWithChildren
  '/_auth/admin/audit-log': typeof AuthAdminAuditLogRoute
  '/_auth/admin/domain-requests': typeof AuthAdminDomainRequestsRoute
  '/_auth/admin/overview': typeof AuthAdminOverviewRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/settings/about': typeof AuthSettingsAboutRoute
  '/_auth/settings/privacy': typeof AuthSettingsPrivacyRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/settings/workspace': typeof AuthSettingsWorkspaceRoute
  '/_auth/teacher/analytics': typeof AuthTeacherAnalyticsRoute
  '/_auth/teacher/calendar': typeof AuthTeacherCalendarRoute
  '/_auth/teacher/dashboard': typeof AuthTeacherDashboardRoute
  '/_auth/teacher/profile': typeof AuthTeacherProfileRoute
  '/_auth/teacher/usage': typeof AuthTeacherUsageRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/teacher/signup/': typeof TeacherSignupIndexRoute
  '/teacher/signup/step-1/create-your-account': typeof TeacherSignupStep1CreateYourAccountRoute
  '/teacher/signup/step-2/verify-your-email': typeof TeacherSignupStep2VerifyYourEmailRoute
  '/teacher/signup/step-3/tell-us-about-you': typeof TeacherSignupStep3TellUsAboutYouRoute
  '/teacher/signup/step-4/your-school': typeof TeacherSignupStep4YourSchoolRoute
  '/teacher/signup/step-5/teaching-levels': typeof TeacherSignupStep5TeachingLevelsRoute
  '/teacher/signup/step-6/welcome-to-agilearn': typeof TeacherSignupStep6WelcomeToAgilearnRoute
  '/_auth/teacher/classrooms/': typeof AuthTeacherClassroomsIndexRoute
  '/_auth/teacher/modules/': typeof AuthTeacherModulesIndexRoute
  '/_auth/teacher/classrooms/$classroomId/grades': typeof AuthTeacherClassroomsClassroomIdGradesRoute
  '/_auth/teacher/classrooms/$classroomId/slideshow': typeof AuthTeacherClassroomsClassroomIdSlideshowRoute
  '/_auth/teacher/classrooms/$classroomId/': typeof AuthTeacherClassroomsClassroomIdIndexRoute
  '/_auth/teacher/classrooms/$classroomId/attendance/$sessionId': typeof AuthTeacherClassroomsClassroomIdAttendanceSessionIdRoute
  '/_auth/teacher/classrooms/$classroomId/attendance/': typeof AuthTeacherClassroomsClassroomIdAttendanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/settings'
    | '/teacher/signup'
    | '/admin/audit-log'
    | '/admin/domain-requests'
    | '/admin/overview'
    | '/admin/users'
    | '/settings/about'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/workspace'
    | '/teacher/analytics'
    | '/teacher/calendar'
    | '/teacher/dashboard'
    | '/teacher/profile'
    | '/teacher/usage'
    | '/settings/'
    | '/teacher/signup/'
    | '/teacher/signup/step-1/create-your-account'
    | '/teacher/signup/step-2/verify-your-email'
    | '/teacher/signup/step-3/tell-us-about-you'
    | '/teacher/signup/step-4/your-school'
    | '/teacher/signup/step-5/teaching-levels'
    | '/teacher/signup/step-6/welcome-to-agilearn'
    | '/teacher/classrooms/'
    | '/teacher/modules/'
    | '/teacher/classrooms/$classroomId/grades'
    | '/teacher/classrooms/$classroomId/slideshow'
    | '/teacher/classrooms/$classroomId/'
    | '/teacher/classrooms/$classroomId/attendance/$sessionId'
    | '/teacher/classrooms/$classroomId/attendance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/admin/audit-log'
    | '/admin/domain-requests'
    | '/admin/overview'
    | '/admin/users'
    | '/settings/about'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/workspace'
    | '/teacher/analytics'
    | '/teacher/calendar'
    | '/teacher/dashboard'
    | '/teacher/profile'
    | '/teacher/usage'
    | '/settings'
    | '/teacher/signup'
    | '/teacher/signup/step-1/create-your-account'
    | '/teacher/signup/step-2/verify-your-email'
    | '/teacher/signup/step-3/tell-us-about-you'
    | '/teacher/signup/step-4/your-school'
    | '/teacher/signup/step-5/teaching-levels'
    | '/teacher/signup/step-6/welcome-to-agilearn'
    | '/teacher/classrooms'
    | '/teacher/modules'
    | '/teacher/classrooms/$classroomId/grades'
    | '/teacher/classrooms/$classroomId/slideshow'
    | '/teacher/classrooms/$classroomId'
    | '/teacher/classrooms/$classroomId/attendance/$sessionId'
    | '/teacher/classrooms/$classroomId/attendance'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_auth/settings'
    | '/teacher/signup'
    | '/_auth/admin/audit-log'
    | '/_auth/admin/domain-requests'
    | '/_auth/admin/overview'
    | '/_auth/admin/users'
    | '/_auth/settings/about'
    | '/_auth/settings/privacy'
    | '/_auth/settings/profile'
    | '/_auth/settings/workspace'
    | '/_auth/teacher/analytics'
    | '/_auth/teacher/calendar'
    | '/_auth/teacher/dashboard'
    | '/_auth/teacher/profile'
    | '/_auth/teacher/usage'
    | '/_auth/settings/'
    | '/teacher/signup/'
    | '/teacher/signup/step-1/create-your-account'
    | '/teacher/signup/step-2/verify-your-email'
    | '/teacher/signup/step-3/tell-us-about-you'
    | '/teacher/signup/step-4/your-school'
    | '/teacher/signup/step-5/teaching-levels'
    | '/teacher/signup/step-6/welcome-to-agilearn'
    | '/_auth/teacher/classrooms/'
    | '/_auth/teacher/modules/'
    | '/_auth/teacher/classrooms/$classroomId/grades'
    | '/_auth/teacher/classrooms/$classroomId/slideshow'
    | '/_auth/teacher/classrooms/$classroomId/'
    | '/_auth/teacher/classrooms/$classroomId/attendance/$sessionId'
    | '/_auth/teacher/classrooms/$classroomId/attendance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TeacherSignupRoute: typeof TeacherSignupRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/signup': {
      id: '/teacher/signup'
      path: '/teacher/signup'
      fullPath: '/teacher/signup'
      preLoaderRoute: typeof TeacherSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/teacher/signup/': {
      id: '/teacher/signup/'
      path: '/'
      fullPath: '/teacher/signup/'
      preLoaderRoute: typeof TeacherSignupIndexRouteImport
      parentRoute: typeof TeacherSignupRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/teacher/usage': {
      id: '/_auth/teacher/usage'
      path: '/teacher/usage'
      fullPath: '/teacher/usage'
      preLoaderRoute: typeof AuthTeacherUsageRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teacher/profile': {
      id: '/_auth/teacher/profile'
      path: '/teacher/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof AuthTeacherProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teacher/dashboard': {
      id: '/_auth/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof AuthTeacherDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teacher/calendar': {
      id: '/_auth/teacher/calendar'
      path: '/teacher/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof AuthTeacherCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teacher/analytics': {
      id: '/_auth/teacher/analytics'
      path: '/teacher/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof AuthTeacherAnalyticsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/workspace': {
      id: '/_auth/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof AuthSettingsWorkspaceRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/privacy': {
      id: '/_auth/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AuthSettingsPrivacyRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/about': {
      id: '/_auth/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AuthSettingsAboutRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/overview': {
      id: '/_auth/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthAdminOverviewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/domain-requests': {
      id: '/_auth/admin/domain-requests'
      path: '/admin/domain-requests'
      fullPath: '/admin/domain-requests'
      preLoaderRoute: typeof AuthAdminDomainRequestsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/audit-log': {
      id: '/_auth/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthAdminAuditLogRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teacher/modules/': {
      id: '/_auth/teacher/modules/'
      path: '/teacher/modules'
      fullPath: '/teacher/modules/'
      preLoaderRoute: typeof AuthTeacherModulesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teacher/classrooms/': {
      id: '/_auth/teacher/classrooms/'
      path: '/teacher/classrooms'
      fullPath: '/teacher/classrooms/'
      preLoaderRoute: typeof AuthTeacherClassroomsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/teacher/signup/step-6/welcome-to-agilearn': {
      id: '/teacher/signup/step-6/welcome-to-agilearn'
      path: '/step-6/welcome-to-agilearn'
      fullPath: '/teacher/signup/step-6/welcome-to-agilearn'
      preLoaderRoute: typeof TeacherSignupStep6WelcomeToAgilearnRouteImport
      parentRoute: typeof TeacherSignupRoute
    }
    '/teacher/signup/step-5/teaching-levels': {
      id: '/teacher/signup/step-5/teaching-levels'
      path: '/step-5/teaching-levels'
      fullPath: '/teacher/signup/step-5/teaching-levels'
      preLoaderRoute: typeof TeacherSignupStep5TeachingLevelsRouteImport
      parentRoute: typeof TeacherSignupRoute
    }
    '/teacher/signup/step-4/your-school': {
      id: '/teacher/signup/step-4/your-school'
      path: '/step-4/your-school'
      fullPath: '/teacher/signup/step-4/your-school'
      preLoaderRoute: typeof TeacherSignupStep4YourSchoolRouteImport
      parentRoute: typeof TeacherSignupRoute
    }
    '/teacher/signup/step-3/tell-us-about-you': {
      id: '/teacher/signup/step-3/tell-us-about-you'
      path: '/step-3/tell-us-about-you'
      fullPath: '/teacher/signup/step-3/tell-us-about-you'
      preLoaderRoute: typeof TeacherSignupStep3TellUsAboutYouRouteImport
      parentRoute: typeof TeacherSignupRoute
    }
    '/teacher/signup/step-2/verify-your-email': {
      id: '/teacher/signup/step-2/verify-your-email'
      path: '/step-2/verify-your-email'
      fullPath: '/teacher/signup/step-2/verify-your-email'
      preLoaderRoute: typeof TeacherSignupStep2VerifyYourEmailRouteImport
      parentRoute: typeof TeacherSignupRoute
    }
    '/teacher/signup/step-1/create-your-account': {
      id: '/teacher/signup/step-1/create-your-account'
      path: '/step-1/create-your-account'
      fullPath: '/teacher/signup/step-1/create-your-account'
      preLoaderRoute: typeof TeacherSignupStep1CreateYourAccountRouteImport
      parentRoute: typeof TeacherSignupRoute
    }
    '/_auth/teacher/classrooms/$classroomId/': {
      id: '/_auth/teacher/classrooms/$classroomId/'
      path: '/teacher/classrooms/$classroomId'
      fullPath: '/teacher/classrooms/$classroomId/'
      preLoaderRoute: typeof AuthTeacherClassroomsClassroomIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teacher/classrooms/$classroomId/slideshow': {
      id: '/_auth/teacher/classrooms/$classroomId/slideshow'
      path: '/teacher/classrooms/$classroomId/slideshow'
      fullPath: '/teacher/classrooms/$classroomId/slideshow'
      preLoaderRoute: typeof AuthTeacherClassroomsClassroomIdSlideshowRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teacher/classrooms/$classroomId/grades': {
      id: '/_auth/teacher/classrooms/$classroomId/grades'
      path: '/teacher/classrooms/$classroomId/grades'
      fullPath: '/teacher/classrooms/$classroomId/grades'
      preLoaderRoute: typeof AuthTeacherClassroomsClassroomIdGradesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teacher/classrooms/$classroomId/attendance/': {
      id: '/_auth/teacher/classrooms/$classroomId/attendance/'
      path: '/teacher/classrooms/$classroomId/attendance'
      fullPath: '/teacher/classrooms/$classroomId/attendance/'
      preLoaderRoute: typeof AuthTeacherClassroomsClassroomIdAttendanceIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teacher/classrooms/$classroomId/attendance/$sessionId': {
      id: '/_auth/teacher/classrooms/$classroomId/attendance/$sessionId'
      path: '/teacher/classrooms/$classroomId/attendance/$sessionId'
      fullPath: '/teacher/classrooms/$classroomId/attendance/$sessionId'
      preLoaderRoute: typeof AuthTeacherClassroomsClassroomIdAttendanceSessionIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthSettingsRouteChildren {
  AuthSettingsAboutRoute: typeof AuthSettingsAboutRoute
  AuthSettingsPrivacyRoute: typeof AuthSettingsPrivacyRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsWorkspaceRoute: typeof AuthSettingsWorkspaceRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsAboutRoute: AuthSettingsAboutRoute,
  AuthSettingsPrivacyRoute: AuthSettingsPrivacyRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsWorkspaceRoute: AuthSettingsWorkspaceRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthRouteChildren {
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthAdminAuditLogRoute: typeof AuthAdminAuditLogRoute
  AuthAdminDomainRequestsRoute: typeof AuthAdminDomainRequestsRoute
  AuthAdminOverviewRoute: typeof AuthAdminOverviewRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthTeacherAnalyticsRoute: typeof AuthTeacherAnalyticsRoute
  AuthTeacherCalendarRoute: typeof AuthTeacherCalendarRoute
  AuthTeacherDashboardRoute: typeof AuthTeacherDashboardRoute
  AuthTeacherProfileRoute: typeof AuthTeacherProfileRoute
  AuthTeacherUsageRoute: typeof AuthTeacherUsageRoute
  AuthTeacherClassroomsIndexRoute: typeof AuthTeacherClassroomsIndexRoute
  AuthTeacherModulesIndexRoute: typeof AuthTeacherModulesIndexRoute
  AuthTeacherClassroomsClassroomIdGradesRoute: typeof AuthTeacherClassroomsClassroomIdGradesRoute
  AuthTeacherClassroomsClassroomIdSlideshowRoute: typeof AuthTeacherClassroomsClassroomIdSlideshowRoute
  AuthTeacherClassroomsClassroomIdIndexRoute: typeof AuthTeacherClassroomsClassroomIdIndexRoute
  AuthTeacherClassroomsClassroomIdAttendanceSessionIdRoute: typeof AuthTeacherClassroomsClassroomIdAttendanceSessionIdRoute
  AuthTeacherClassroomsClassroomIdAttendanceIndexRoute: typeof AuthTeacherClassroomsClassroomIdAttendanceIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthAdminAuditLogRoute: AuthAdminAuditLogRoute,
  AuthAdminDomainRequestsRoute: AuthAdminDomainRequestsRoute,
  AuthAdminOverviewRoute: AuthAdminOverviewRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthTeacherAnalyticsRoute: AuthTeacherAnalyticsRoute,
  AuthTeacherCalendarRoute: AuthTeacherCalendarRoute,
  AuthTeacherDashboardRoute: AuthTeacherDashboardRoute,
  AuthTeacherProfileRoute: AuthTeacherProfileRoute,
  AuthTeacherUsageRoute: AuthTeacherUsageRoute,
  AuthTeacherClassroomsIndexRoute: AuthTeacherClassroomsIndexRoute,
  AuthTeacherModulesIndexRoute: AuthTeacherModulesIndexRoute,
  AuthTeacherClassroomsClassroomIdGradesRoute:
    AuthTeacherClassroomsClassroomIdGradesRoute,
  AuthTeacherClassroomsClassroomIdSlideshowRoute:
    AuthTeacherClassroomsClassroomIdSlideshowRoute,
  AuthTeacherClassroomsClassroomIdIndexRoute:
    AuthTeacherClassroomsClassroomIdIndexRoute,
  AuthTeacherClassroomsClassroomIdAttendanceSessionIdRoute:
    AuthTeacherClassroomsClassroomIdAttendanceSessionIdRoute,
  AuthTeacherClassroomsClassroomIdAttendanceIndexRoute:
    AuthTeacherClassroomsClassroomIdAttendanceIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TeacherSignupRouteChildren {
  TeacherSignupIndexRoute: typeof TeacherSignupIndexRoute
  TeacherSignupStep1CreateYourAccountRoute: typeof TeacherSignupStep1CreateYourAccountRoute
  TeacherSignupStep2VerifyYourEmailRoute: typeof TeacherSignupStep2VerifyYourEmailRoute
  TeacherSignupStep3TellUsAboutYouRoute: typeof TeacherSignupStep3TellUsAboutYouRoute
  TeacherSignupStep4YourSchoolRoute: typeof TeacherSignupStep4YourSchoolRoute
  TeacherSignupStep5TeachingLevelsRoute: typeof TeacherSignupStep5TeachingLevelsRoute
  TeacherSignupStep6WelcomeToAgilearnRoute: typeof TeacherSignupStep6WelcomeToAgilearnRoute
}

const TeacherSignupRouteChildren: TeacherSignupRouteChildren = {
  TeacherSignupIndexRoute: TeacherSignupIndexRoute,
  TeacherSignupStep1CreateYourAccountRoute:
    TeacherSignupStep1CreateYourAccountRoute,
  TeacherSignupStep2VerifyYourEmailRoute:
    TeacherSignupStep2VerifyYourEmailRoute,
  TeacherSignupStep3TellUsAboutYouRoute: TeacherSignupStep3TellUsAboutYouRoute,
  TeacherSignupStep4YourSchoolRoute: TeacherSignupStep4YourSchoolRoute,
  TeacherSignupStep5TeachingLevelsRoute: TeacherSignupStep5TeachingLevelsRoute,
  TeacherSignupStep6WelcomeToAgilearnRoute:
    TeacherSignupStep6WelcomeToAgilearnRoute,
}

const TeacherSignupRouteWithChildren = TeacherSignupRoute._addFileChildren(
  TeacherSignupRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TeacherSignupRoute: TeacherSignupRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
